// Conservative V1 defaults. Future calibration should adjust this module
// without rewriting the Conviction Engine formulas themselves.
export const DEFAULT_CONVICTION_CONFIG = {
  finalConvictionWeights: {
    holderIntegrity: 0.22,
    walletQuality: 0.18,
    behaviorStability: 0.18,
    liquidityTrust: 0.15,
    marketMomentum: 0.12,
    riskProtection: 0.15,
  },
  walletQualityWeights: {
    maturity: 0.2,
    activity: 0.12,
    convictionBehavior: 0.3,
    concentrationProtection: 0.14,
    dormancyProtection: 0.1,
    botProtection: 0.1,
    clusterProtection: 0.04,
  },
  walletMaturity: {
    veryFreshDays: 7,
    freshDays: 30,
    mediumDays: 90,
    matureDays: 365,
    veryFreshScore: 12,
    freshScore: 28,
    mediumScore: 52,
    matureScore: 76,
    veryMatureScore: 92,
    freshWalletPenalty: 24,
    systemWalletPenalty: 10,
  },
  dormancyRisk: {
    veryRecentDays: 2,
    recentDays: 7,
    mediumDays: 30,
    elevatedDays: 90,
    veryRecentScore: 8,
    recentScore: 22,
    mediumScore: 45,
    elevatedScore: 68,
    highScore: 88,
    fallbackDays: 45,
  },
  concentrationRisk: {
    baseOwnershipMultiplier: 25,
    onePercentThreshold: 1,
    fivePercentThreshold: 5,
    tenPercentThreshold: 10,
    onePercentPenaltyMultiplier: 5,
    fivePercentPenaltyMultiplier: 7,
    tenPercentPenaltyMultiplier: 8,
  },
  liquidityTrust: {
    unavailableScore: 35,
    baseScore: 40,
    logLiquidityWeight: 9,
    maxLogLiquidityScore: 42,
    liquidityRatioWeight: 180,
    maxLiquidityRatioScore: 28,
    healthyVolumeLiquidityBonus: 12,
    healthyVolumeLiquidityMin: 0.1,
    healthyVolumeLiquidityMax: 4,
    lowLiquidityThresholdUsd: 25_000,
    lowLiquidityPenalty: 30,
    highMarketCapThresholdUsd: 10_000_000,
    weakLiquidityRatioThreshold: 0.015,
    weakLiquidityPenalty: 24,
    extremeVolumeLiquidityRatio: 8,
    extremeVolumePenalty: 24,
  },
  severeRiskPenalties: {
    insiderRiskThreshold: 85,
    clusterRiskThreshold: 85,
    botActivityRiskThreshold: 85,
    finalScorePenalty: 22,
  },
  finalConvictionCaps: {
    lowLiquidityTrustThreshold: 20,
    lowLiquidityMaxConviction: 55,
    lowHolderIntegrityThreshold: 20,
    lowHolderIntegrityMaxConviction: 45,
  },
} as const;

export const SYNTHETIC_SCENARIO_EXPECTED_RANGES = {
  "Rug Pull": { min: 0, max: 25 },
  "Fresh Wallet Farm": { min: 10, max: 35 },
  "Bot Farm": { min: 10, max: 40 },
  "Whale Concentration": { min: 20, max: 50 },
  "Organic Community": { min: 65, max: 85 },
  "Diamond Hands": { min: 75, max: 95 },
  "Healthy Growth": { min: 70, max: 90 },
  "Exchange Dominated": { min: 40, max: 70 },
} as const;
